### PR TITLE
V4.2.1

### PR DESCRIPTION
**Pull request by definite**
Upgrade to V4.2.1
and made following changes:
1. Add the environment variables to standalone.xml
2. Match the mysql version with the zanata-platform.
3. Make runapp.sh more closer to rundev in zanata-platform.

Perhaps next release, we should use jboss-cli to simplify the standalone.xml configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-docker-files/21)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[zanata-server/common, line 9 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2Yj_1ov__69hNdyMd:-Kn2Yj_1ov__69hNdyMe:b-4nuv81) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/common#L9)):*
> ```
> 
> # default docker network to join
> : ${ZANATA_DOCKER_NETWORK:=docker-network}
> ```

'docker-network' as default docker network name seems too vague. It's fine for dev environment since we only have one network. For Zanata production instance, maybe we should rename the default to something more meaningful. e.g. zanata-network?

---

*[zanata-server/runapp.sh, line 13 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2YKeiYFyWPwROzgDL:-Kn2YKeiYFyWPwROzgDM:b-r8bjn1) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/runapp.sh#L13)):*
> ```Shell
> 
> # default mail setting
> : ${ZANATA_MAIL_HOST:=localhost}
> ```

I think we should make ZANATA_MAIL_HOST mandatory. localhost in a container pretty much means it won't work. For Zanata prod instance to work properly you kind of always need to have email setup correctly

---

*[zanata-server/conf/standalone.xml, line 36 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZR9EOYkDSQxQtJrc:-Kn2ZR9EOYkDSQxQtJrd:bh61b7q) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L36)):*
> ```XML
> 
>     <system-properties>
>         <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5InnoDBDialect" />
> ```

I don't think we use this property

---

*[zanata-server/conf/standalone.xml, line 45 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZDnxVDizL8tHNFZb:-Kn2ZDnxVDizL8tHNFZc:bo6hdn6) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L45)):*
> ```XML
>         <property name="zanata.email.defaultfromaddress" value="no-reply@zanata.org" />
>         <property name="zanata.file.directory" value="${env.ZANATA_HOME:/var/lib/zanata}/files" />
>         <property name="zanata.support.oauth" value="true" />
> ```

we probably don't need this in prod. At the moment only Zanata sync uses this field.

---

*[zanata-server/conf/standalone.xml, line 141 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2Ze1kzCh_MUOLzS4Y:-Kn2Ze1kzCh_MUOLzS4Z:bog4kyy) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L141)):*
> ```XML
>             <logger category="io.undertow.security">
>                 <level name="TRACE"/>
>             </logger>
> ```

We don't need these two log category in prod

---

*[zanata-server/conf/standalone.xml, line 175 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZkSYSobAWLtVSI4s:-Kn2ZkSYSobAWLtVSI4t:b-k7sbaw) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L175)):*
> ```XML
>             <logger category="jacorb.config">
>                 <level name="DEBUG" />
>                 <filter-spec value="any(match(&quot;.*Catching.*&quot;), levelRange[INFO, FATAL])" />
> ```

this change should not be here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21)*

**Comment by definite** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[zanata-server/common, line 9 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2Yj_1ov__69hNdyMd:-Kn2fSdGmtpNkKqotT1S:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/common#L9)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

'docker-network' as default docker network name seems too vague. It's fine for dev environment since we only have one network. For Zanata production instance, maybe we should rename the default to something more meaningful. e.g. zanata-network?
</blockquote></details>

Done.

---

*[zanata-server/runapp.sh, line 13 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2YKeiYFyWPwROzgDL:-Kn2fUKUcbV1mcs416an:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/runapp.sh#L13)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I think we should make ZANATA_MAIL_HOST mandatory. localhost in a container pretty much means it won't work. For Zanata prod instance to work properly you kind of always need to have email setup correctly
</blockquote></details>

Done.

---

*[zanata-server/conf/standalone.xml, line 36 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZR9EOYkDSQxQtJrc:-Kn2fgpPj-oHTcsQeNAk:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L36)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

I don't think we use this property
</blockquote></details>

Done.

---

*[zanata-server/conf/standalone.xml, line 45 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZDnxVDizL8tHNFZb:-Kn2ffmatFpUHuzkRfqV:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L45)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

we probably don't need this in prod. At the moment only Zanata sync uses this field.
</blockquote></details>

Done.

---

*[zanata-server/conf/standalone.xml, line 141 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2Ze1kzCh_MUOLzS4Y:-Kn2fiGNqyNV6_iz0qDy:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L141)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

We don't need these two log category in prod
</blockquote></details>

Done.

---

*[zanata-server/conf/standalone.xml, line 175 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZkSYSobAWLtVSI4s:-Kn2fj-_tnLFSvBv-4JN:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L175)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

this change should not be here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21)*

**Comment by huangp** [comment]
Reviewed 1 of 7 files at r1, 2 of 3 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[zanata-server/conf/standalone.xml, line 175 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZkSYSobAWLtVSI4s:-Kn2oUiRPUg0YTuak7YJ:b-8h4nqm) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L175)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We still want the jacorb.config log. Just leave the level to ERROR

---

*[zanata-server/conf/standalone.xml, line 134 at r2](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2oJe2NmMtpUb5PAS5:-Kn2oJe3LoBsmU39Qm8o:booz3lf) ([raw file](https://github.com/zanata/zanata-docker-files/blob/fcf84034313a0d877efa0f8a2024f0bfff51f1d4/zanata-server/conf/standalone.xml#L134)):*
> ```XML
>                 <level name="DEBUG" />
>             </logger>
>             <logger category="org.jboss.security.auth.spi.AbstractServerLoginModule">
> ```

remove this one as well please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21)*

**Comment by definite** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[zanata-server/conf/standalone.xml, line 175 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZkSYSobAWLtVSI4s:-Kn2tTScguyNeWJ6Z2I6:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L175)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

We still want the jacorb.config log. Just leave the level to ERROR
</blockquote></details>

Done.

---

*[zanata-server/conf/standalone.xml, line 134 at r2](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2oJe2NmMtpUb5PAS5:-Kn2tFmVQ_QIY4oqJLEG:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/fcf84034313a0d877efa0f8a2024f0bfff51f1d4/zanata-server/conf/standalone.xml#L134)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

remove this one as well please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21)*

**Comment by huangp** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[zanata-server/conf/standalone.xml, line 175 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZkSYSobAWLtVSI4s:-Kn2uhjCfAwTSXZr8HeU:bxiz0pn) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L175)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Should be 
```
<logger category="jacorb.config">
    <level name="ERROR" />
</logger>
```

---

*[zanata-server/conf/standalone.xml, line 134 at r2](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2oJe2NmMtpUb5PAS5:-Kn2uAEu5KU7E659K00J:bmqh30t) ([raw file](https://github.com/zanata/zanata-docker-files/blob/fcf84034313a0d877efa0f8a2024f0bfff51f1d4/zanata-server/conf/standalone.xml#L134)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still there. For prod instance there should be no TRACE or DEBUG logging turn on by default. Only a small amount of INFO logging for certain category. So we should remove the entire category "org.jboss.as.config" or change the level to WARNING. 
Also apply to above two categories. I think they are copied as is from dev instance. We should remove them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21)*

**Comment by definite** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[zanata-server/conf/standalone.xml, line 175 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2ZkSYSobAWLtVSI4s:-Kn39ptEk7FuRBJKOw9z:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/eb34f0c34499ecbb509f32c78492e3ec9aa937a5/zanata-server/conf/standalone.xml#L175)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Should be 
```
<logger category="jacorb.config">
    <level name="ERROR" />
</logger>
```
</blockquote></details>

Done.

---

*[zanata-server/conf/standalone.xml, line 134 at r2](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-Kn2oJe2NmMtpUb5PAS5:-Kn39rDLlPsHWLzSi6K3:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/fcf84034313a0d877efa0f8a2024f0bfff51f1d4/zanata-server/conf/standalone.xml#L134)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

It's still there. For prod instance there should be no TRACE or DEBUG logging turn on by default. Only a small amount of INFO logging for certain category. So we should remove the entire category "org.jboss.as.config" or change the level to WARNING. 
Also apply to above two categories. I think they are copied as is from dev instance. We should remove them.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/21#-:-Kn3BGApqzyyIUyievhp:b-ew2adl)*

**Pull request merged**
