### PR TITLE
ZNTA-2081: Configure SMTP (port, TLS, SSL, Authentication) with environment variables

### PR DESCRIPTION
**Pull request by tholu**
JIRA issue [here](https://zanata.atlassian.net/browse/ZNTA-2081)

Adds support to configure various SMTP variables (including authentication, TLS and SSL) and information in the README.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-docker-files/26)

### CODE REVIEW

**Review by seanf — APPROVED** [review]
Looks good, thanks @tholu!

**Comment by spathare21** [comment]
@tholu unable to run the container using ./runapp.sh it is asking 

$./runapp.sh -e mail_host
==== use empt.redhat.com as mail host ====
b6cd14b5e515        zanata-network      bridge              local
will use docker network zanata-network
Preparing container for Zanata (latest)
zanata-files
./runapp.sh: line 117: ZANATA_MAIL_USERNAME: unbound variable 

same happeing for if i provided 

$./runapp.sh -e mailhost -l username:pass 
/runapp.sh: line 117: ZANATA_MAIL_TLS: unbound variable

I am not sure about about to provide TLS value to runapp.sh

can you please add more information in README. better if you add example for how to run

**Comment by tholu** [comment]
@spathare21 Thanks for the feedback, I'll check and get back to you.

**Comment by tholu** [comment]
@spathare21 I fixed it among other issues (e.g. with `DOCKER_NETWORK` variable) I discovered, please check and merge if everything is ok. Thanks!

**Comment by spathare21** [comment]
@tholu are you able to run the app before merging your changes, I am getting following errors

[logs_before_merge.txt](https://github.com/zanata/zanata-docker-files/files/1578094/logs_before_merge.txt)


after merging your changes I am getting following logs 

[logs_after-merge.txt](https://github.com/zanata/zanata-docker-files/files/1578096/logs_after-merge.txt)

#### steps followed : 
- cd zanata-docker-files/zanata-server
- docker build -t zanata-server .
- ./runapp.sh -e mail-host

**Comment by tholu** [comment]
@spathare21 Thanks for checking, I think I know what I missed (did not build the image locally, so it used the docker image from the repository). I will check again & fix it!

**Comment by tholu** [comment]
@spathare21 After checking out my branch with the latest fix, you should be able to test it like that:

```
cd zanata-docker-files/zanata-server
docker build -t zanata-server .
./runapp.sh
```

or

```
cd zanata-docker-files/zanata-server
docker build -t zanata-server .
docker-compose up
```

Both worked fine for me. Thanks for your feedback!

**Comment by spathare21** [comment]
@tholu not sure whats wrong but i am getting error after ./runapp.sh 

`ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 65) MSC000001: Failed to start service jboss.persistenceunit."zanata.war#zanataDatasourcePU": org.jboss.msc.service.StartException in service jboss.persistenceunit."zanata.war#zanataDatasourcePU": org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
`
here is the all logs 
[logs.txt](https://github.com/zanata/zanata-docker-files/files/1581631/logs.txt)

**Comment by tholu** [comment]
@spathare21 It somehow cannot connect to your `zanatadb` instance. Do you have any docker containers running when executing `runapp.sh`? What does `docker info` say?

**Comment by tholu** [comment]
@seanf Can you also test the changes to see if this issue is reproducible?

**Comment by spathare21** [comment]
@tholu yes my zanatadb container is running

**Comment by tholu** [comment]
@spathare21 Try stopping and removing the `zanatadb` cointainer. Please give me the full output of the `runapp.sh` command, as well as for `sudo docker info`.

**Comment by spathare21** [comment]
@tholu here is the all logs. 

[logs_runapp.txt](https://github.com/zanata/zanata-docker-files/files/1582016/logs_runapp.txt)

**Comment by tholu** [comment]
@spathare21 Please try the following:

```
sudo docker stop zanatadb
sudo docker rm zanatadb
sudo docker ps
sudo docker info
./runapp.sh
```

And send me the full output of all commands.

**Comment by spathare21** [comment]
Hi @tholu ,
I followed the steps mentioned by you and below is the o/p

`[spathare@dhcp201-168 zanata-server]$ sudo docker stop zanatadb
[sudo] password for spathare: 
zanatadb
[spathare@dhcp201-168 zanata-server]$ sudo docker rm zanatadb
zanatadb
[spathare@dhcp201-168 zanata-server]$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[spathare@dhcp201-168 zanata-server]$ sudo docker info
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 68
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-253:0-2492313-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.257GB
 Data Space Total: 107.4GB
 Data Space Available: 1.71GB
 Metadata Space Used: 7.66MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 1.71GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.12.5-300.fc26.x86_64
Operating System: Fedora 26 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.31GiB
Name: dhcp201-168.englab.pnq.redhat.com
ID: L3D3:TTUR:3SVX:LXWX:466L:RJ4V:IV35:YM3G:DVMK:4FL7:ZBDU:VG6A
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
[spathare@dhcp201-168 zanata-server]$ 
$ ./runapp.sh 
creating docker network zanata-network
87aa6aa1acdd95fdd3ad49c7e5c76ec2622b7fda640177a851a293e8f808ec8d
87aa6aa1acdd        zanata-network      bridge              local
will use docker network zanata-network
zanata-db
Error response from daemon: No such container: zanatadb
Error: failed to start containers: zanatadb

`

**Comment by tholu** [comment]
Not sure what is happening here, but I will investigate, so we can finish the PR soon.

**Comment by tholu** [comment]
@spathare21 Can you please try to run `./rundb.sh` separately and see if this works? Somehow your database container does not start up.

@seanf Can you please test as well? For me, everything is running just fine. Please help get this PR merged, thank you!

**Comment by tholu** [comment]
@definite Can you also please test/review this PR? Thank you!

**Comment by alex-sl-eng** [comment]
@tholu Might require to rebase this branch due to https://github.com/zanata/zanata-docker-files/pull/28

**Comment by tholu** [comment]
@aeng Thanks for the hint, I merged the master to resolve the conflicts. Can you test if you have the same problems as @spathare21 had? Thanks!

**Comment by spathare21** [comment]
thanks, @tholu now it working fine by following the same steps mentioned above 
by running runapp.sh after building zanata/server docker image. 

@djansen-redhat or @definite take a look if you have time. marking it as verified.

**Comment by tholu** [comment]
Thank you! Is the latest image already pushed to the Docker Hub?

**Comment by definite** [comment]
@tholu Yes. on this time, you can either use 4.4.3-2 or latest for the latest image.

**Pull request merged**
