### PR TITLE
doc(ZNTA-1435): Update Docker image document

### PR DESCRIPTION
**Pull request by definite**
https://zanata.atlassian.net/browse/ZNTA-1435 

This depends on https://zanata.atlassian.net/browse/ZNTA-1380
(docker-images PR #9)

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/docker-images/10)

### CODE REVIEW

**Comment by davidmason** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[zanata-server/README.md, line 6 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVT8uZlWbG8whaRO0H:-KUVT8uZlWbG8whaRO0I:brg0nr6) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L6)):_

> ``` Markdown
> is required.
> 
> Assume you have checkout this repository, and `cd zanata-server`.
> ```

Suggest "The following instructions assume that you have cloned this repository and opened a terminal  in the `zanata-server` directory.

---

_[zanata-server/README.md, line 17 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVTe-ruVK4P9ImkwYt:-KUVTe-ruVK4P9ImkwYu:bc00upv) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L17)):_

> ``` Markdown
> ```
> 
> You can also specify version you want to build, for example, 3.9.5, with following command:
> 
> ```
> ```

"... specify the version you want to build. For example, you can build version 3.9.5 with the following command:"

---

_[zanata-server/README.md, line 22 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVTvdOrUUOg4tcH8Re:-KUVTvdOrUUOg4tcH8Rf:bd2hh2h) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L22)):_

> ``` Markdown
> ```
> 
> Note that for older version, you may need to edit `standalone.xml` to make Zanata works.
> 
> ```
> ```

"... older versions ..."
"... to make Zanata work."

---

_[zanata-server/README.md, line 26 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVU81qot8Jnj_FACV0:-KUVU81qot8Jnj_FACV1:b-6xckl2) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L26)):_

> ``` Markdown
> ## Setup Environment
> Those environment variables are used in helper scripts.
> Override them to suit your need.
> ```

"These ..."
"... in the helper scripts."
"... your needs."

---

_[zanata-server/README.md, line 31 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVUL6dJECdVAl2JR_P:-KUVUL6dJECdVAl2JR_Q:b-ewh4z8) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L31)):_

> ``` Markdown
> * `ZANATA_MYSQL_USER`: Zanata uses this username to access database in MariaDB. (Default: `zanata`)
> * `ZANATA_MYSQL_PASSWORD`: Zanata uses this password to access database in MariaDB. (Default: `password`)
> * `ZANATA_PORT`: Zanata listens this port on the host. (Default: `8080`)
> ```

"... listens to this port..." or "... listens on this port..."

---

_[zanata-server/README.md, line 32 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVUVBuKU9601gbrtL4:-KUVUVBuKU9601gbrtL5:bte8f3l) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L32)):_

> ``` Markdown
> * `ZANATA_MYSQL_PASSWORD`: Zanata uses this password to access database in MariaDB. (Default: `password`)
> * `ZANATA_PORT`: Zanata listens this port on the host. (Default: `8080`)
> * `ZANATA_DAEMON_MODE`: If non empty, the Zanata is run as daemon, otherwise, it runs in frontend and print log to console. (Default: `1`)
> ```

"... empty, Zanata is..."
"... in the foreground and prints its log directly to the console."

Where does the log get printed if it is a daemon?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by davidmason** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[zanata-server/README.md, line 37 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVV0lh1oCtFzw60MNG:-KUVV0lh1oCtFzw60MNH:bw9jbba) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L37)):_

> ``` Markdown
> ## Run Database as docker container
> 
> Zanata uses MariaDB or MySQL as database backend. 
> ```

"... as its database..."

---

_[zanata-server/README.md, line 45 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVVK-3oXPl99eJu7zx:-KUVVK-3oXPl99eJu7zy:b-whd91h) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L45)):_

> ``` Markdown
> 
> ## Run Zanata as docker container
> Run the following command to start the wildfly container with Zanata in tow. It will link the database container (`--link`) named `zanatadb` (same name which was given to the database container above) to the alias `db`.
> ```

Is "in tow" something technical about docker? If not, we should state this more plainly.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by davidmason** [comment]
Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[zanata-server/README.md, line 61 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVWVOKpQd3vjDy7y-0:-KUVWVOLaZw1DCMsES8j:b-jyzhee) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L61)):_

> ``` Markdown
> ```
> 
> where `DB_IP` is IP address of `zanatadb`. You do need to type the Zanata Maridb password
> 
> ```
> ```

Do we need the sentence "You do not need to...", or can we just not mention it?

---

_[zanata-server/README.md, line 65 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVWtSDEUl8iYzp-G7L:-KUVWtSDEUl8iYzp-G7M:b-y20ajx) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L65)):_

> ``` Markdown
> 
> ## Access Zanata
> Open a browser and head to `http://HOST:PORT/zanata`, where `PORT` is the port determined in the previous step, and `HOST` is the docker host's address (this might be `localhost` or some other IP address if running on OSX for example).
> ```

There is no port determined in the previous step. Where should someone find the port?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by davidmason** [comment]
Review status: 0 of 3 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

_[zanata-server/runapp.sh, line 7 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVXLeQ3Pr04g2xzeur:-KUVXLeQ3Pr04g2xzeus:b-n9v1jd) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/runapp.sh#L7)):_

> ``` Shell
> else
>     ZanataVer=$(sed -r -n -e '/^ARG\s+ZANATA_VERSION/ s/^ARG\s+ZANATA_VERSION\s*=\s*(.*)\s*/\1/p' < $ScriptDir/Dockerfile)
> fi
> ```

Please add a comment that says what this `iffi` block does.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by davidmason** [comment]
Review status: 0 of 3 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

_[zanata-server/rundb.sh, line 2 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVXqaKNT7wbjU_r3hC:-KUVXqaKNT7wbjU_r3hD:biszgsi) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/rundb.sh#L2)):_

> ``` Shell
> #!/bin/bash -eu
> ### This program setups the data volume and database containers for Zanata
> ```

"...program sets up the..."

---

_[zanata-server/rundb.sh, line 8 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVY1effLXUvxmOOYo6:-KUVY1effLXUvxmOOYo7:bmmnmyt) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/rundb.sh#L8)):_

> ``` Shell
> : ${ZANATA_MYSQL_DATABASE:=zanata}
> 
> ## Create missing data volume
> ```

Would "Create zanata data volume if it is missing" be accurate?

---

_[zanata-server/rundb.sh, line 13 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVYYltZO4Qd0VUP4wi:-KUVYYltZO4Qd0VUP4wj:b-wqf3xt) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/rundb.sh#L13)):_

> ``` Shell
> fi
> 
> ## Run container when no container named zanatadb
> ```

Please add more information to this comment. What is the difference between the two branches here?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by davidmason** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by definite** [comment]
Review status: 0 of 2 files reviewed at latest revision, 14 unresolved discussions.

---

_[zanata-server/README.md, line 6 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVT8uZlWbG8whaRO0H:-KUVaPuJN4XidxLKrO7N:b-896fix) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L6)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> Suggest "The following instructions assume that you have cloned this repository and opened a terminal  in the `zanata-server` directory.
> </details>
> Done.

---

_[zanata-server/README.md, line 17 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVTe-ruVK4P9ImkwYt:-KUVaQhurbwtcjlmqQ6o:b-896fix) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L17)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> "... specify the version you want to build. For example, you can build version 3.9.5 with the following command:"
> </details>
> Done.

---

_[zanata-server/README.md, line 22 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVTvdOrUUOg4tcH8Re:-KUVaRFQJZrswbJ3fVxb:b-896fix) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L22)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> "... older versions ..."
> "... to make Zanata work."
> </details>
> Done.

---

_[zanata-server/README.md, line 26 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVU81qot8Jnj_FACV0:-KUVaReNUZJTvfoSBYtK:b-896fix) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L26)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> "These ..."
> "... in the helper scripts."
> "... your needs."
> </details>
> Done.

---

_[zanata-server/README.md, line 31 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVUL6dJECdVAl2JR_P:-KUVaS2lhFqsumr4fEqJ:b-896fix) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L31)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> "... listens to this port..." or "... listens on this port..."
> </details>
> Done.

---

_[zanata-server/README.md, line 32 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVUVBuKU9601gbrtL4:-KUV_sGGubGLJ1bE5V4c:bnd9gvr) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L32)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> "... empty, Zanata is..."
> "... in the foreground and prints its log directly to the console."
> 
> Where does the log get printed if it is a daemon?
> </details>
> On daemon mode, the log can be viewed by `docker logs zanata`.  Come to think of it, I probably need to set ZANATA_DAEMON_MODE=1 as daemon mode, and everything else is none daemon mode.

---

_[zanata-server/README.md, line 37 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVV0lh1oCtFzw60MNG:-KUVaVy3Yidfk8zVWjDR:b-896fix) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L37)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> "... as its database..."
> </details>
> Done.

---

_[zanata-server/README.md, line 45 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVVK-3oXPl99eJu7zx:-KUVaWx1Ow9YLpMlMJ6Q:b4trroi) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L45)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> Is "in tow" something technical about docker? If not, we should state this more plainly.
> </details>
> Mmm, I should change this part, as `runapp.sh` invokes `rundb.sh` if container `zanatadb` is not running.

---

_[zanata-server/README.md, line 61 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVWVOKpQd3vjDy7y-0:-KUVkUjqP762oNvx4Bmw:b2chi4k) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L61)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> Do we need the sentence "You do not need to...", or can we just not mention it?
> </details>
> You DO need to ...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by davidmason** [comment]
Reviewed 1 of 3 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

_[zanata-server/README.md, line 32 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVUVBuKU9601gbrtL4:-KUVpu3HB_SMo_KQQuBO:blvppm) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L32)):_
<details><summary>

<i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>



> On daemon mode, the log can be viewed by `docker logs zanata`.  Come to think of it, I probably need to set ZANATA_DAEMON_MODE=1 as daemon mode, and everything else is none daemon mode.
> </details>
> Remember the grammar fixes for this as well.

---

_[zanata-server/README.md, line 37 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVV0lh1oCtFzw60MNG:-KUVq7gtwi_5rgMD3C0r:b-cq9hmx) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L37)):_
<details><summary>

<i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>



> Done.
> </details>
> Looks more like you deleted the whole section. Is that on purpose?

---

_[zanata-server/README.md, line 61 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVWVOKpQd3vjDy7y-0:-KUVr2MT6DLdFlOvE_7y:b-g0ubwi) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L61)):_
<details><summary>

<i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>



> You DO need to ...
> </details>
> Oops. I read it wrong because usually I wouldn't expect "do" at all unless it is to say "do not". I suggest we change it to "You will need to..." to avoid this type of mis-reading.

---

_[zanata-server/README.md, line 43 at r2](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVqQSYtuo2Df76a-6m:-KUVqQSZN821bSsFc-LH:bd2w3tk) ([raw file](https://github.com/zanata/docker-images/blob/2fb9a6a3b420b767b1f0f82ade7df9ed2a13bd93/zanata-server/README.md#L43)):_

> ``` Markdown
> 
> It will not only start the Zanata, but also invokes data and database (MariaDB or MySQL) containers if they are not already running.
> See `rundb.sh` for the invocation detail.
> ```

This doesn't need the first part, so it can just be something like: "If the database container is not running, this will start the database container as well."

Are there separate containers `data` and `database`?  I thought there was just one container for the database.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by davidmason** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by definite** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[zanata-server/README.md, line 37 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVV0lh1oCtFzw60MNG:-KUW7U8-M76dlwxITyR8:bp31kft) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L37)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> Looks more like you deleted the whole section. Is that on purpose?
> </details>
> Yes, as the `runapp.sh` invokes `rundb.sh` automatically, the is no need to mention the database set up section.

---

_[zanata-server/README.md, line 45 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVVK-3oXPl99eJu7zx:-KUW88lygpHJ6JXNYrOq:b-896fix) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/README.md#L45)):_
<details><summary>

<i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>



> Mmm, I should change this part, as `runapp.sh` invokes `rundb.sh` if container `zanatadb` is not running.
> </details>
> Done.

---

_[zanata-server/README.md, line 43 at r2](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVqQSYtuo2Df76a-6m:-KUW8NMxrhEkGtesEEXT:b-r96wek) ([raw file](https://github.com/zanata/docker-images/blob/2fb9a6a3b420b767b1f0f82ade7df9ed2a13bd93/zanata-server/README.md#L43)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> This doesn't need the first part, so it can just be something like: "If the database container is not running, this will start the database container as well."
> 
> Are there separate containers `data` and `database`?  I thought there was just one container for the database.
> </details>
> Actually, there are 2 containers: `zanata-data` for data volume (file storage) and `zanatadb` for database. Perhaps I should call them data containers.

---

_[zanata-server/runapp.sh, line 7 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUVXLeQ3Pr04g2xzeur:-KUWA73JeYSeVryT49de:b-896fix) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/runapp.sh#L7)):_
<details><summary>

<i>Previously, davidmason (David Mason) wrote…</i></summary>



> Please add a comment that says what this `iffi` block does.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by davidmason** [comment]
This just needs a review of the docker invocations in rundb.sh and runapp.sh by someone who has done docker training.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10#-:-KUZgD_vbqnAqi8tiW9n:b-w5g7wy)_

**Comment by davidmason** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[zanata-server/rundb.sh, line 10 at r1](https://reviewable.io:443/reviews/zanata/docker-images/10#-KUZjkt_Kkwj8oUm-EJm:-KUZjkt_Kkwj8oUm-EJn:bygpkx7) ([raw file](https://github.com/zanata/docker-images/blob/7f5ef5a56ed9f019684bb5dd4f4db9dc68e62f86/zanata-server/rundb.sh#L10)):_

> ``` Shell
> ## Create missing data volume
> if ! (docker volume ls -q | grep zanata-data) ; then
>     docker volume create --name zanata-data
> ```

Someone with more docker experience than me should review all the docker commands in here and runapp.sh

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10)_

**Comment by huangp** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10#-:-KVwMSXN7L1bTtj8YCaM:bnfp4nl)_

**Comment by davidmason** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/10#-:-KVwMXtpEKXXx2Js3DEI:bnfp4nl)_

**Pull request merged**
