### PR TITLE
feat(ZNTA-2333): image-make should support pre-release

### PR DESCRIPTION
**Pull request by definite**
https://zanata.atlassian.net/browse/ZNTA-2333

As well as necessary changes for 4.4.0

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-docker-files/30)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-server/conf/standalone.xml, line 46 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/30#-L2sK4pjCHm9TwmRTNEO:-L2sK4pkZkQGsVvaY6f3:b-o2iwca) ([raw file](https://github.com/zanata/zanata-docker-files/blob/21c52f537dd75ec883f906d31e8c8fe2d4b9899e/zanata-server/conf/standalone.xml#L46)):*
> ```XML
>         <property name="zanata.security.authpolicy.internal" value="zanata.internal" />
>         <property name="zanata.security.authpolicy.openid" value="zanata.openid" />
>         <property name="zanata.security.authpolicy.saml2" value="zanata.saml2" />
> ```

SAML2 should be optional. I think we can comment out this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/30)*

**Comment by huangp** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[zanata-server/conf/standalone.xml, line 39 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/30#-L2sKBAzfw0yrfs3R8TE:-L2sKBAzfw0yrfs3R8TF:b-qwwrn) ([raw file](https://github.com/zanata/zanata-docker-files/blob/21c52f537dd75ec883f906d31e8c8fe2d4b9899e/zanata-server/conf/standalone.xml#L39)):*
> ```XML
>         <property name="javamelody.storage-directory" value="${env.ZANATA_HOME:/var/lib/zanata}/stats" />
>         <property name="jboss.as.management.blocking.timeout" value="1000" />
>         <property name="picketlink.file" value="${env.ZANATA_HOME:/var/lib/zanata}/picketlink.xml" />
> ```

This is optional. We should comment out this line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/30)*

**Comment by definite** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[zanata-server/conf/standalone.xml, line 39 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/30#-L2sKBAzfw0yrfs3R8TE:-L2sX4CX88j5dLTnokS7:b-896fix) ([raw file](https://github.com/zanata/zanata-docker-files/blob/21c52f537dd75ec883f906d31e8c8fe2d4b9899e/zanata-server/conf/standalone.xml#L39)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

This is optional. We should comment out this line
</blockquote></details>

Done.

---

*[zanata-server/conf/standalone.xml, line 46 at r1](https://reviewable.io:443/reviews/zanata/zanata-docker-files/30#-L2sK4pjCHm9TwmRTNEO:-L2sX0E8F2mU5Qe6Ralw:bb6un1j) ([raw file](https://github.com/zanata/zanata-docker-files/blob/21c52f537dd75ec883f906d31e8c8fe2d4b9899e/zanata-server/conf/standalone.xml#L46)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

SAML2 should be optional. I think we can comment out this line.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/30)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/30#-:-L2wBpXOLkwV5tQUnzVH:b-ew2adl)*

**Pull request merged**
