### PR TITLE
ZNTA-1147 Update to Zanata 3.8.4

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1147

This change is [Reviewable](https://reviewable.io/reviews/zanata/docker-images/3)

### CODE REVIEW

**Comment by definite** [comment]
:lgtm:

<details><summary>

<i>Previously, seanf (Sean Flanigan) wrote…</i></summary>



> #### ZNTA-1147 Update to Zanata 3.8.4
> 
> https://zanata.atlassian.net/browse/ZNTA-1147
> 
> </details>

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/3#-:-KJYztm5gThLTkt43XZO:1417088721)_

**Comment by seanf** [comment]
Thanks @definite. 
@carlosmunoz I'd like your input too.

**Comment by carlosmunoz** [comment]
:lgtm_strong: 

<details><summary>

<i>Previously, seanf (Sean Flanigan) wrote…</i></summary>



> Thanks @definite. 
> 
> @carlosmunoz I'd like your input too.
> </details>

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[zanata-server/Dockerfile, line 10 [r2]](https://reviewable.io:443/reviews/zanata/docker-images/3#-KJZ7iuMAaiGggFckK0O:-KJZ7iuNaMq5jX0H6k3Q:1914565418) ([raw file](https://github.com/zanata/docker-images/blob/2fe3d26df7e9b60715387005b616c1d19ba533cc/zanata-server/Dockerfile#L10)):_

> ``` Dockerfile
> # Wildfly modules
> 
> RUN wget --no-verbose https://dl.bintray.com/sflanigan/generic/wildfly-module-hibernate-main-4.2.20.Final.zip \
> ```

should we (someday) change this to a Zanata bintray?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/3#-:-KJZ8Dvz97pgt8JZGLOW:-1868698381)_

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[zanata-server/Dockerfile, line 10 [r2]](https://reviewable.io:443/reviews/zanata/docker-images/3#-KJZ7iuMAaiGggFckK0O:-KJZBkTTBN-hUl6vGH7v:-1163408235) ([raw file](https://github.com/zanata/docker-images/blob/2fe3d26df7e9b60715387005b616c1d19ba533cc/zanata-server/Dockerfile#L10)):_
<details><summary>

<i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>



> should we (someday) change this to a Zanata bintray?
> </details>
> We could, but I'd rather we just eliminated the need for this module, and made Zanata work with Hibernate 4 _and_ 5.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/3)_

**Pull request merged**
