### PR TITLE
ZNTA-1148 Use MySQL 5.7 and UTF-8

### PR DESCRIPTION
**Pull request by seanf**
Until https://jira.mariadb.org/browse/MDEV-9646 is implemented, this is the only way to index large varchar fields without code changes to Zanata (or Liquibase) if you want real UTF-8.

https://zanata.atlassian.net/browse/ZNTA-1148

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/docker-images/4)

### CODE REVIEW

**Comment by definite** [comment]
:lgtm:

<details><summary>

<i>Previously, seanf (Sean Flanigan) wrote…</i></summary>



> #### ZNTA-1148 Use MySQL 5.7 and UTF-8
> 
> Until https://jira.mariadb.org/browse/MDEV-9646 is implemented, this is the only way to index large varchar fields without code changes to Zanata (or Liquibase) if you want real UTF-8.
> 
> </details>

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/4#-:-KJZ7_N6biuZo0D3GJ-A:1417088721)_

**Comment by definite** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/4)_

**Comment by definite** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/4)_

**Comment by definite** [comment]
:lgtm:

<details><summary>

<i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>



> :lgtm:
> </details>

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/4#-:-KJsjn6qLMRu37DIWcJi:1417088721)_

**Comment by seanf** [comment]
We're not planning to switch Zanata from mariadb to mysql at this stage, so I'm going to close this pull request.

But if anyone urgently needs full UTF-8 support, running the docker image `mysql:5.7` with parameters `--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci` should work for now. Example command:

```
docker run --name zanatadb \
  -e MYSQL_USER=zanata -e MYSQL_PASSWORD=password -e MYSQL_DATABASE=zanata -e MYSQL_RANDOM_ROOT_PASSWORD=yes \
  -d mysql:5.7 \
  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

**However**, note that you might get issues in future if you need to switch your existing database files from running with MySQL 5.7 to MariaDB. It depends on how compatible they stay.

**Pull request closed without merging**
