### PR TITLE
feat(ZNTA-1471) add docker-compose.yml

### PR DESCRIPTION
**Pull request by SlavikZ**
Jira Issue: [ZNTA-1471](https://zanata.atlassian.net/browse/ZNTA-1471) 

Add docker-compose.yml file as `runapp.sh`, `rundb.sh` scripts replacement for those who prefer to use docker-compose tool.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-docker-files/20)

### CODE REVIEW

**Review by carlosmunoz — APPROVED** [review]

**Comment by seanf** [comment]
See also #23, since Fedora 24 (for one) doesn't support docker-compose 2.1 files. But I think there are other problems relating to Zanata 4.2.1 (and/or Docker 1.10+) which we also need to deal with.

**Comment by carlosmunoz** [comment]
@seanf so what's the plan for this PR?

**Comment by seanf** [comment]
The first step is for someone should see if they can get the Zanata 4.2.1 image to work with Docker 1.10+. Then we can decide between #20 and #23. 

Unfortunately @definite is on leave. I'm not sure what combinations he tested for Zanata 4.2.1.

**Comment by jurikolo** [comment]
Hey,
I've adjusted initial docker-compose with support for docker in Fedora 27. Sources: https://github.com/jurikolo/zanata/blob/master/docker-compose.yml

**Comment by carlosmunoz** [comment]
@seanf @djansen-redhat @spathare21 This has been dormant for a while. What's the plan with this PR?

**Comment by tholu** [comment]
Would be really nice to have this as well, we have been fighting with Zanata Docker images as well.

**Comment by seanf** [comment]
@jurikolo Were your changes to take advantage of improvements in Fedora 27, or did @SlavikZ 's version break on Fedora 27?

It appears that docker-compose v3 files don't support depends_on with health checks, so it would be a shame to lose that. https://github.com/peter-evans/docker-compose-healthcheck/issues/3#issuecomment-329037485

**Comment by seanf** [comment]
Please see #23 which is based on this PR. Thanks @SlavikZ and @jurikolo

**Pull request closed without merging**
