### PR TITLE
zanata 3.9.0 docker image

### PR DESCRIPTION
**Pull request by carlosmunoz**
Update the docker image to Zanata 3.9 and Wildfly. The standalone.xml is based off the one used in Zanata overlay at the time of release.

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/docker-images/6)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[zanata-server/Dockerfile, line 13 [r1]](https://reviewable.io:443/reviews/zanata/docker-images/6#-KLoA72_VkJLUJTxrUxR:-KLoA72_VkJLUJTxrUxS:1625332191) ([raw file](https://github.com/zanata/docker-images/blob/68d09e9e0ad65479ae8c82e92cb2b6d15abb6537/zanata-server/Dockerfile#L13)):_

> ``` Dockerfile
>     && unzip -q wildfly-module-hibernate-main-4.2.20.Final.zip -d /opt/jboss/wildfly
> 
> ENV ZANATA_VERSION 3.9.0
> ```

I think we should go straight to 3.9.1, given the transaction bugs in 3.9.0.

---

_[zanata-server/conf/standalone.xml, line 178 [r1]](https://reviewable.io:443/reviews/zanata/docker-images/6#-KLoAZSrqyzVWbZjHr7N:-KLoAZSrqyzVWbZjHr7O:-704888101) ([raw file](https://github.com/zanata/docker-images/blob/68d09e9e0ad65479ae8c82e92cb2b6d15abb6537/zanata-server/conf/standalone.xml#L178)):_

> ``` XML
>             <formatter name="COLOR-PATTERN">
>                 <pattern-formatter
>                   pattern="%K{level}%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n" />
> ```

These log formatters no longer use UTC timestamps, but I suppose that's okay.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/6)_

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[zanata-server/conf/standalone.xml, line 178 [r1]](https://reviewable.io:443/reviews/zanata/docker-images/6#-KLoc8nBgC2m-nqCZ9QK:-KLoc8nCkeFJ-4DBbm7x:1929858279) ([raw file](https://github.com/zanata/docker-images/blob/68d09e9e0ad65479ae8c82e92cb2b6d15abb6537/zanata-server/conf/standalone.xml#L178)):_

> ``` XML
>             <formatter name="COLOR-PATTERN">
>                 <pattern-formatter
>                   pattern="%K{level}%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n" />
> ```

While we're in here, I would recommend we use `%E` instead of `%e`, so that we get the jar name (and version) in our stack traces. I plan to make the same change in other places.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/6)_

**Comment by carlosmunoz** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[zanata-server/Dockerfile, line 13 [r1]](https://reviewable.io:443/reviews/zanata/docker-images/6#-KLoA72_VkJLUJTxrUxR:-KMRDbOKwyQRjgJtJTxY:-499146009) ([raw file](https://github.com/zanata/docker-images/blob/68d09e9e0ad65479ae8c82e92cb2b6d15abb6537/zanata-server/Dockerfile#L13)):_
<details><summary>

<i>Previously, seanf (Sean Flanigan) wrote…</i></summary>



> I think we should go straight to 3.9.1, given the transaction bugs in 3.9.0.
> </details>
> Done.

---

_[zanata-server/conf/standalone.xml, line 178 [r1]](https://reviewable.io:443/reviews/zanata/docker-images/6#-KLoc8nBgC2m-nqCZ9QK:-KMRDewYZ3nd-CxK9xqE:-499146009) ([raw file](https://github.com/zanata/docker-images/blob/68d09e9e0ad65479ae8c82e92cb2b6d15abb6537/zanata-server/conf/standalone.xml#L178)):_
<details><summary>

<i>Previously, seanf (Sean Flanigan) wrote…</i></summary>



> While we're in here, I would recommend we use `%E` instead of `%e`, so that we get the jar name (and version) in our stack traces. I plan to make the same change in other places.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/6)_

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/6#-:-KMRk9fwBCNdgxwdu6kG:1417088721)_

**Pull request merged**
