### PR TITLE
Use realpath instead of readlink for MacOS compability

### PR DESCRIPTION
**Pull request by definite**
Part of https://zanata.atlassian.net/browse/ZNTA-1660
ZNTA-1660: Update docker script to avoid 'chcon' error

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-docker-files/17)

### CODE REVIEW

**Comment by ghost** [comment]
@definite the script starts but after downloading the image it gives me an error: http://pastebin.test.redhat.com/453253

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/17#-:-KcPouuCVv6_vDJPtD89:b-h0pugp)*

**Comment by ghost** [comment]
@definite, still doesn't work if I delete the WAR files in docker-volumes/zanata-deployments 
Same error: 
`docker: Error response from daemon: Cannot link to /zanatadb, as it does not belong to the default network.`

**Comment by definite** [comment]
@kathryngo You might need to run following
docker rm -f zanatadb
docker volume rm zanata-db

**Comment by ghost** [comment]
That worked
LGTM

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/17#-:-KcVQqpzoXx3tG-itAyg:b-gmszye)*

**Review by ghost — APPROVED** [review]

**Comment by djansen-redhat** [comment]
✅ Taking the above comment and my own test on Fedora as verified

**Pull request merged**
