### PR TITLE
Update docker-compose for Zanata 4.2+

### PR DESCRIPTION
**Pull request by seanf**
Based on #20 and parts of https://github.com/jurikolo/zanata/blob/3906624e35b5aa8fae355d3e305f4e226afa6807/docker-compose.yml.

This docker-compose file uses v2.1 format, which is available in Docker 1.13.1+ (Fedora 26+). https://docs.docker.com/compose/compose-file/compose-versioning/

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-docker-files/23)

### CODE REVIEW

**Comment by definite** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-docker-files/23#-:-KzbAw5Q8gZD8L8eiDgZ:bnfp4nl)*

**Comment by tholu** [comment]
Can you add those variables to the .env file (perhaps commented)?

```
ZANATA_DAEMON_MODE=
ZANATA_MAIL_HOST=
ZANATA_MAIL_PORT=
ZANATA_MAIL_USERNAME=
ZANATA_MAIL_PASSWORD=
```

**Comment by seanf** [comment]
@tholu Can you elaborate? I don't think putting them in the .env file file would do anything by itself, because "Environment variables defined in the .env file are not automatically visible inside containers." - https://docs.docker.com/compose/env-file/#compose-file-and-cli-variables

I think it would be best to tackle these extras in a separate pull request.

**Comment by seanf** [comment]
We've done a bit of smoke testing on this, but, as usual, let us know if there's a problem with the docker images/config.

Thanks for the contributions @SlavikZ and @jurikolo.

**Comment by tholu** [comment]
@seanf Of course they would have to be provided in the `docker-compose.yml` file as well, right now it's not immediately clear from documentation, that these can be configured at all.

```
  environment:
      - MAIL_HOST=${ZANATA_MAIL_HOST}
      - MAIL_PORT=${ZANATA_MAIL_PORT}
      - MAIL_USERNAME=${ZANATA_MAIL_USERNAME}
      - MAIL_PASSWORD=${ZANATA_MAIL_PASSWORD}
      - [...]
```

**Pull request merged**
