### PR TITLE
ZNTA-2081: Configure SMTP port with environment variable

### PR DESCRIPTION
**Pull request by hmbrg**
JIRA issue [here](https://zanata.atlassian.net/browse/ZNTA-2081)
Adds support to configure the SMTP port and information in the README.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-docker-files/22)

### CODE REVIEW

**Review by seanf — APPROVED** [review]

**Comment by seanf** [comment]
@brighthero I gather the TLS aspect of the JIRA issue is yet to be addressed?

**Comment by hmbrg** [comment]
@seanf Yes, that is correct.

Is changing the standalone.xml how I did it correct?
```xml
<subsystem xmlns="urn:jboss:domain:mail:2.0">
            <mail-session name="default" jndi-name="java:jboss/mail/Default">
                <smtp-server outbound-socket-binding-ref="mail-smtp"  tls="true" username="${env.MAIL_USERNAME: }" password="${env.MAIL_PASSWORD: }"/>
            </mail-session>
        </subsystem>
````
If so, configuring that would be easy with an environment variable.

**Comment by seanf** [comment]
@brighthero Yes, that looks right, as far as I can tell. If we insert this into the `smtp-server` element, it should work with the default port 25 (since SMTP on port 25 is probably non-TLS).

    tls="${env.MAIL_TLS:false}"

**Comment by seanf** [comment]
@brighthero Could you please enable the option "Allow edits from maintainers" on this pull request? Then we'll be able to make the changes in your branch directly. (https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)

Thanks.

**Comment by tholu** [comment]
@seanf @brighthero It would be nice to include the MAIL environment variables in `docker-compose.yml` in this pull request! See #23

**Comment by tholu** [comment]
See my extended PR here: #26. Feel free to edit it as well, thanks!

**Comment by hmbrg** [comment]
@seanf Edits by maintainers are now allowed. Sorry for the delay.

**Comment by seanf** [comment]
Thanks for the PR. It looks like @tholu's PR covers the changes I was planning, and more, so I'm closing this one in favour of #26.

**Comment by alex-sl-eng** [comment]
:+1:

**Pull request closed without merging**
