### PR TITLE
ZNTA-1380: data volumes for persistence

### PR DESCRIPTION
**Pull request by definite**
https://zanata.atlassian.net/browse/ZNTA-1380

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/docker-images/9)

### CODE REVIEW

**Comment by huangp** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[zanata-server/runapp.sh, line 7 at r1](https://reviewable.io:443/reviews/zanata/docker-images/9#-KUUtM_TuIJXsdrRNups:-KUUtM_TuIJXsdrRNupt:btn1wlf) ([raw file](https://github.com/zanata/docker-images/blob/3abe5a2eb2243bab4ea747b6d507f674482f5c7f/zanata-server/runapp.sh#L7)):_

> ``` Shell
> else
>     ZanataVer=$(sed -r -n -e '/^ARG\s+ZANATA_VERSION/ s/^ARG\s+ZANATA_VERSION\s*=\s*(.*)\s*/\1/p' < $ScriptDir/Dockerfile)
> fi
> ```

Having a comment to explain this if block will help

---

_[zanata-server/runapp.sh, line 9 at r1](https://reviewable.io:443/reviews/zanata/docker-images/9#-KUUsofOgBZf04EWMVTO:-KUUsofOgBZf04EWMVTP:bwj2mes) ([raw file](https://github.com/zanata/docker-images/blob/3abe5a2eb2243bab4ea747b6d507f674482f5c7f/zanata-server/runapp.sh#L9)):_

> ``` Shell
> fi
> 
> : ${ZANATA_PORT:=8080}
> ```

What does this mean? the : at the front.

---

_[zanata-server/runapp.sh, line 17 at r1](https://reviewable.io:443/reviews/zanata/docker-images/9#-KUUsls57M_i9l2G5s70:-KUUsls57M_i9l2G5s71:bhoi1cu) ([raw file](https://github.com/zanata/docker-images/blob/3abe5a2eb2243bab4ea747b6d507f674482f5c7f/zanata-server/runapp.sh#L17)):_

> ``` Shell
>     DockerOptArray+=( -d )
> else
>     DockerOptArray+=( --rm  -it )
> ```

Do you need `-it` here?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/9)_

**Comment by definite** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[zanata-server/runapp.sh, line 9 at r1](https://reviewable.io:443/reviews/zanata/docker-images/9#-KUUsofOgBZf04EWMVTO:-KUUzugmZLpg7pmkFBCS:b-1t8bxo) ([raw file](https://github.com/zanata/docker-images/blob/3abe5a2eb2243bab4ea747b6d507f674482f5c7f/zanata-server/runapp.sh#L9)):_
<details><summary>

<i>Previously, huangp (Patrick Huang) wrote…</i></summary>



> What does this mean? the : at the front.
> </details>
> `:` in bash means Null command.  Parameter expansion `${ZANATA_PORT:=8080}` cannot live by themselves. 

---

_[zanata-server/runapp.sh, line 17 at r1](https://reviewable.io:443/reviews/zanata/docker-images/9#-KUUsls57M_i9l2G5s70:-KUV-scaeFESQuoEWkwE:bmj0zmz) ([raw file](https://github.com/zanata/docker-images/blob/3abe5a2eb2243bab4ea747b6d507f674482f5c7f/zanata-server/runapp.sh#L17)):_
<details><summary>

<i>Previously, huangp (Patrick Huang) wrote…</i></summary>



> Do you need `-it` here?
> </details>
> `ZANATA_DAEMON_MODE` not `1` means the Zanata should print the log message in the front end. But I just notices that my script may break when  `ZANATA_DAEMON_MODE=0`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/9)_

**Comment by huangp** [comment]
:lgtm: -(Awaiting review)  +Reviewed 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/9#-:-KUVAQ5oY73qMhHR08gG:b-loqpvf)_

**Comment by definite** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[zanata-server/runapp.sh, line 7 at r1](https://reviewable.io:443/reviews/zanata/docker-images/9#-KUUtM_TuIJXsdrRNups:-KUVBC-AlDBhuYOrJCa3:b-896fix) ([raw file](https://github.com/zanata/docker-images/blob/3abe5a2eb2243bab4ea747b6d507f674482f5c7f/zanata-server/runapp.sh#L7)):_
<details><summary>

<i>Previously, huangp (Patrick Huang) wrote…</i></summary>



> Having a comment to explain this if block will help
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/docker-images/9)_

**Pull request merged**
